### ISSUE TITLE
Server Side Modules Failing Build (ModuleNotFoundError)

### ISSUE THREAD

**Issue by RealDrewKlayman** [aws-amplify/amplify-hosting#2098]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d22wer5oad5zkl

### Region

us-east-2

### Amplify Console feature

Other - SSR Building (Webpack)

### Describe the bug

argon2 

Build fails with message:
```
ModuleNotFoundError: Module not found: Error: Can't resolve 'mock-aws-s3' in '/codebuild/output/src886526768/src/nextjs-amplify-import-error/node_modules/@mapbox/node-pre-gyp/lib/util'
```

### Expected behavior

It should ignore that module since it is a server side module.

The build should not fail (more information in Additional Information section)

### Reproduction steps

To skip all these steps you can just clone this repository: https://github.com/RealDrewKlayman/nextjs-amplify-import-error

1. Run `npx create-next-app --typescript`.
2. Move everything `pages` and `styles` into a new folder called `src`.
3. Install argon2 (this package is one I know that has dependencies) `npm install argon2`.
4. Update the `src/pages/api/hello.ts` file to this:
```
// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import argon2 from 'argon2'
import type { NextApiRequest, NextApiResponse } from 'next'

type Data = {
  password: string
}

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse<Data>
) {

  const hashedPassword = await argon2.hash('secret password');
  res.status(200).json({ password: hashedPassword })
}
``` 
(This is just a simple API route I made using that module)
5. Push/Deploy to Amplify

### Build Settings

```yaml
- Next Version: `latest`
```

### Additional information

https://arunoda.me/blog/ssr-and-server-only-modules
That's an old article explaining why these modules should not be included in the build. It's old so it claims that NextJS doesn't know how to handle this but Vercel and local builds handle it perfectly.

A workaround is to add all these modules in ignorePlugin in Webpack which is not ideal at all.

**Comment by RealDrewKlayman** [comment]
This issue was discussed on the Discord and posted here..

Tagging @siegerts

**Comment by NathaEEUD** [comment]
Hi :wave:, I'm getting the same behavior in a NextJS project using the `next-auth` package which is coupled with the serverless function `api/auth/[...nextauth].js` 

The error message is:

```
ModuleNotFoundError: Module not found: Error: Can't resolve 'mongodb' in '/codebuild/output/src441885191/src/nextjs-frontend/node_modules/typeorm/platform'
```

**Comment by jackHedaya** [comment]
@NathaEEUD I believe we have the same problem! My issue is opened in #2103

**Comment by RealDrewKlayman** [comment]
> Hi 👋, I'm getting the same behavior in a NextJS project using the `next-auth` package which is coupled with the serverless function `api/auth/[...nextauth].js`
> 
> The error message is:
> 
> ```
> ModuleNotFoundError: Module not found: Error: Can't resolve 'mongodb' in '/codebuild/output/src441885191/src/nextjs-frontend/node_modules/typeorm/platform'
> ```



> @NathaEEUD I believe we have the same problem! My issue is opened in #2103

Yep, these both appear to be because of this issue.

**Comment by NathaEEUD** [comment]
> @NathaEEUD I believe we have the same problem! My issue is opened in #2103

@jackHedaya Have you found any alternative solution to solve this issue? (while the issue is fixed)

**Comment by jackHedaya** [comment]
Nothing yet, waiting it out until I could find the root of the issue

**Comment by RealDrewKlayman** [comment]
Well, what do we do?

**Comment by RealDrewKlayman** [comment]
@Athena96 Can you tag this as bug?

**Comment by sonofole** [comment]
We also ran into this on our project and it's a massive blocker for us. We've tested pretty exhaustively mixing and matching different versions of Webpack, NextJS, Node, etc and nothing is working. Anything you can do to expedite a fix (or provide instructions for a workaround) would be greatly appreciated!

**Comment by siegerts** [comment]
Hi All, first of all, thanks for raising and providing details both here and on Discord. Apologies if this a blocker - The team is looking into this.

If your environment/project setup is different than @RealDrewKlayman's repro example above (or linked issues), please add here. Specifics to include are the combination of:

- what module is throwing the error (`argon2`, `mongodb`, `mock-aws-s3`, etc.)
- webpack version ([4 or 5](https://nextjs.org/docs/messages/webpack5))
- Next.js version 
- new or existing app
- etc.

**Comment by RealDrewKlayman** [comment]
@siegerts @Athena96 
I hope this helps with fixing this issue..
I was able to get it working with argon2 by changing my next.config to this:
```
module.exports = {
  reactStrictMode: true,

  webpack: (config, { buildId, dev, isServer, defaultLoaders, webpack }) => {
    config.externals = config.externals || [];
    config.externals = [...config.externals, 'argon2']
    return config
  },
}
```
Here is the branch: https://github.com/RealDrewKlayman/nextjs-amplify-import-error/tree/fix-error

**Comment by Athena96** [comment]
Hi @RealDrewKlayman , sorry you are facing this. We have identified an issue with how we bundle modules with newer versions of webpack5 and Next.js for the server side lambdas. We are working on a resolution and will follow up here when we have an update.
Regarding the `argon2` library, this has [known issues](https://tg4.solutions/how-to-resolve-invalid-elf-header-error/) running on Lambdas, we suggest you try another similar library like 'bcrypt' or look into using a [custom build image](https://docs.aws.amazon.com/amplify/latest/userguide/custom-build-image.html) like the article suggests.

**Comment by RealDrewKlayman** [comment]
> Hi @RealDrewKlayman , sorry you are facing this. We have identified an issue with how we bundle modules with newer versions of webpack5 and Next.js for the server side lambdas. We are working on a resolution and will follow up here when we have an update.
> 
> Regarding the `argon2` library, this has [known issues](https://tg4.solutions/how-to-resolve-invalid-elf-header-error/) running on Lambdas, we suggest you try another similar library like 'bcrypt' or look into using a [custom build image](https://docs.aws.amazon.com/amplify/latest/userguide/custom-build-image.html) like the article suggests.

Thank you for keeping me in the loop. My team was just asking if I had an update so I really appreciate this...

As for the Argon2 error, the only reason that started happening was because I added the externals onto the webpack. I believe that once the build is fixed this will also fix itself.

Is there a workaround I can put in my app in the meantime?

**Comment by RealDrewKlayman** [comment]
We wouldn't be able to differ from Argon2 because in the project we are using it in, it has to verify an Argon2 hash so I'll look into those articles you sent.

**Comment by marlonmarcello** [comment]
Having the same issue here. My set up is the same as @NathaEEUD 
I am using NextJS 11 and Webpack 4 with NextAuth.
To answer @siegerts 
- what module is throwing the error
  - I think it's happening to any module that is dynamically imported
- webpack version (4 or 5)
  - 4
- Next.js version
  - 11.0.1
- new or existing app
  - new

Like I mentioned before, I am also using NextAuth v3.27.3.
Right now I can't run any builds and the project is getting delayed. I'll gladly provide any other information you might need.

**Comment by liamegan** [comment]
We're also seeing this happen at App ID `d133c0az9frtms`.

**Comment by mwiekens** [comment]
I'm having the same problem.

I got errors that it couldn't find libraries.

First it was: @sls-next/serverless-undefined. Which I solved using a different Amplify Cli version.

Then it gave me errors on:
- sass
- @zeit/next-sass
- @zeit/next-less
- @zeit/next-stylus
Which seem to be old libraries NextJS used in an older version?

I tried added them to package.json. But then eventually it couldn't find webpack.

Currently is is failing on dependency: sass.

I do use SASS, but Next exports the application fine.

I am using:
- NextJS: 11.0.0
- Amplify Cli: 5.3.0
- Webpack: 5
- React: 17.0.2

**Comment by RealDrewKlayman** [comment]
@Athena96 Any update on this? It's still a big blocker..

**Comment by RealDrewKlayman** [comment]
My work-around which isn't really a work-around:
I had to move the code that was using Argon2 onto our main server and in the SSR route I had to call that API route. Which kind of defeats the point of having everything related to this feature in one area but we had no alternative.

**Comment by liamegan** [comment]
Any updates on this?

Our workaround, just so we could keep developing, was to remove nextauth completely. Not really an option for production at which time we're hoping this is resolved. Otherwise we need to find an alternative to Amplify.

**Comment by RealDrewKlayman** [comment]
> Any updates on this?
> 
> Our workaround, just so we could keep developing, was to remove nextauth completely. Not really an option for production at which time we're hoping this is resolved. Otherwise we need to find an alternative to Amplify.

Our team sent an email to Amplify asking if for an update and we got a reply from @Athena96 yesterday saying:

```
Hi Drew,
 
Yes we are aware of the module import issues (leading to the build failures you are seeing) customers are experiencing with the upgrade to webpack5.

We are working on an update to make the module imports more seamless. We’re posting updates here: https://github.com/aws-amplify/amplify-console/issues/2098#issuecomment-893898449

But will notify you as well when these improvements are deployed.
 
Thanks,
Jared
```

**Comment by hughesjj** [comment]
I'm having similar issues after adding sentry to my application.  If anyone has a working sentry configuration (one which avoids this issue), please let me know.  

```

2021-08-16T23:26:57.588Z [INFO]: Page                             Size     First Load JS
                                 ┌ λ /                            23.1 kB         125 kB
                                 ├   /_app                        0 B             101 kB
                                 ├ λ /404                         1.17 kB         103 kB
                                 └ ○ /posts/[name]                308 B           102 kB
                                 + First Load JS shared by all    101 kB
                                 ├ chunks/framework.09a88f.js   42.4 kB
                                 ├ chunks/main.d02058.js        23.4 kB
                                 ├ chunks/pages/_app.b0653e.js  34.6 kB
                                 └ chunks/webpack.cb643f.js     1.01 kB
2021-08-16T23:26:57.589Z [INFO]: λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
                                 ○  (Static)  automatically rendered as static HTML (uses no initial props)
                                 ●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
                                 (ISR)     incremental static regeneration (uses revalidate in getStaticProps)
2021-08-16T23:26:57.693Z [INFO]: Starting SSR Build...
2021-08-16T23:28:07.509Z [ERROR]: Error: Command failed with exit code 1: node_modules/.bin/next build
                                  Failed to compile.
                                  ModuleNotFoundError: Module not found: Error: Can't resolve 'webpack' in '/codebuild/output/src986514351/src/hughesjj--blog/frontend/node_modules/@next/react-refresh-utils'
                                  > Build error occurred
                                  Error: > Build failed because of webpack errors
                                  at /codebuild/output/src986514351/src/hughesjj--blog/frontend/node_modules/next/dist/build/index.js:390:19
                                  at async Span.traceAsyncFn (/codebuild/output/src986514351/src/hughesjj--blog/frontend/node_modules/next/dist/telemetry/trace/trace.js:60:20)
                                  info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
                                  info  - Checking validity of types...
                                  info  - Creating an optimized production build...
                                  at makeError (/root/.//node_modules/execa/lib/error.js:60:11)
                                  at handlePromise (/root/.//node_modules/execa/index.js:118:26)
                                  at processTicksAndRejections (internal/process/task_queues.js:97:5)
                                  at async Builder.build (/root/.//node_modules/@sls-next/lambda-at-edge/dist/build.js:358:13) {
                                  shortMessage: 'Command failed with exit code 1: node_modules/.bin/next build',
                                  command: 'node_modules/.bin/next build',
                                  escapedCommand: '"node_modules/.bin/next" build',
                                  exitCode: 1,
                                  signal: undefined,
                                  signalDescription: undefined,
                                  stdout: 'info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5\n' +
                                  'info  - Checking validity of types...\n' +
                                  'info  - Creating an optimized production build...',
                                  stderr: 'Failed to compile.\n' +
                                  '\n' +
                                  "ModuleNotFoundError: Module not found: Error: Can't resolve 'webpack' in '/codebuild/output/src986514351/src/hughesjj--blog/frontend/node_modules/@next/react-refresh-utils'\n" +
                                  '\n' +
                                  '\n' +
                                  '> Build error occurred\n' +
                                  'Error: > Build failed because of webpack errors\n' +
                                  '    at /codebuild/output/src986514351/src/hughesjj--blog/frontend/node_modules/next/dist/build/index.js:390:19\n' +
                                  '    at async Span.traceAsyncFn (/codebuild/output/src986514351/src/hughesjj--blog/frontend/node_modules/next/dist/telemetry/trace/trace.js:60:20)',
                                  failed: true,
                                  timedOut: false,
                                  isCanceled: false,
                                  killed: false
                                  }
2021-08-16T23:28:07.511Z [ERROR]: [G[?25h[G[J
                                  48s › d3g7909ozl32ry › Error: Command failed with exit code 1: node_modules/.bin/next build
                                  Failed to compile.
                                  ModuleNotFoundError: Module not found: Error: Can't resolve 'webpack' in '/codebuild/output/src986514351/src/hughesjj--blog/frontend/node_modules/@next/react-refresh-utils'
                                  > Build error occurred
                                  Error: > Build failed because of webpack errors
                                  at /codebuild/output/src986514351/src/hughesjj--blog/frontend/node_modules/next/dist/build/index.js:390:19
                                  at async Span.traceAsyncFn (/codebuild/output/src986514351/src/hughesjj--blog/frontend/node_modules/next/dist/telemetry/trace/trace.js:60:20)
                                  info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
                                  info  - Checking validity of types...
                                  info  - Creating an optimized production build...
                                  [G[?25h
Terminating logging...
```

**Comment by liamegan** [comment]
We've ended up having to move to Vercel here. Not ideal as everything else to do with the application is within the AWS sandbox, but there it is.

**Comment by RealDrewKlayman** [comment]
Any update @siegerts @Athena96 ?

**Comment by parkerthegeniuschild** [comment]
what module is throwing the error?
` canvas`

webpack version (4 or 5)
` 5`

Next.js version
` 11`

new or existing app
` new app`

Build image
` default Amazon Linux 2`

Extra
`canvas is not listed in package.json but also fails when listed or added to webpack ignorePlugins too`

**Comment by mwiekens** [comment]
> I'm having similar issues after adding sentry to my application. If anyone has a working sentry configuration (one which avoids this issue), please let me know.
> 


I use Sentry as well. Next-sentry to be exact.

**Comment by nicksemansonos** [comment]
We're having this issue as well, both with webpack version 4 and 5. 

What module is throwing the error?
With webpack 5, `_http_common`
With webpack 4, `jose`

webpack version (4 or 5)
`5, but have tried 4 as well as a potential workaround to no avail`

Next.js version
`11.1, but have tried 11.0 and 10.2.3 too`

New or existing app
`New`

Build image
`default build image`

Extra
Using `next-auth` and `prisma` on the API routes. Happy to provide a bit more detail if needed.

**Comment by nicksemansonos** [comment]
Update: we were able to get our app deployed successfully after downgrading `prisma` and `@prisma/client` to v2.18 in case anyone else is using this dependency. Haven't narrowed it down to the exact version that broke yet but I can confirm the build works perfectly with 2.18 and fails with the error we're all describing on the latest `2.29.1`

**Comment by MartinCura** [comment]
Hi. I'll add another dependency that causes the `Cannot find module 'webpack'` error on SSR Build: `next-pwa@5.3.1`.
This after setting Next.js version to `latest` in Amplify as recommended (using 11.0.1).

**Comment by Athena96** [comment]
### Webpack / Cannot find Module / ModuleNotFound / NotImplemented
Hi @RealDrewKlayman and others,
If you are facing Webpack errors (Cannot find module/ ModuleNotFound) as a result of the new Webpack 5 default, or the "A header you provided implies functionality ..." NotImplemented Error.
Can you try the following:
1. Try a Next.js 10 version  e.g. `"next": "10.2.3",` in `package.json`
2. Create a `next.config.js` file if you don't already have one and add the `target: 'serverless'` param like so:
```
module.exports = {
    target: 'serverless',
}
```

**Comment by RealDrewKlayman** [comment]
Hello? @Athena96 @siegerts

**Comment by VidorX** [comment]
Also facing this issue with 'electron' module:

what module is throwing the error?
electron

webpack version (4 or 5)
4

Next.js version
11

new or existing app
new app

Build image
default Amazon Linux 2

**Comment by VidorX** [comment]
Temporary fix to ignore the plugin allows build to succeed: 

In next.config.js:

`config.plugins.push(new webpack.IgnorePlugin(/^electron$/));`

**Comment by RealDrewKlayman** [comment]
> Temporary fix to ignore the plugin allows build to succeed: 
> 
> 
> 
> In next.config.js:
> 
> 
> 
> `config.plugins.push(new webpack.IgnorePlugin(/^electron$/));`
> 
> 

In some cases it will be a never ending journey. I ignored one and then another popped up and that went on for like 10+ and then I gave up.

**Comment by jtmthf** [comment]
What worked for me was to opt out of webpack5 when using Next 11.

```ts
// next.config.js

module.exports = {
  webpack5: false,
};
```

**Comment by LakedaemonLive** [comment]
Any progress on resolving this?  I've tried all the suggested work-arounds with no success.  I'm using next-auth and it is triggering the error.  I've tried the webpack 5 false and target serverless.  I've also tried ignoring includes, but that ended up chasing over a dozen modules with no end in sight.

**Comment by ovdahlberg** [comment]
We are facing the same issue with Sentry on Next.js 11 with Webpack 5.

**Comment by ferdingler** [comment]
Hi everyone, we are adding support for deploying NextJS apps with the `experimental-serverless-trace` target. We have seen that this target fixes issues with the webpack bundle when using server side modules (i.e. argon).

In the interest of being extra careful and preserving backwards compatibility, we are not going to make this the default target yet. So for those having webpack issues, you will need to opt-in into this feature by specifying the target in your `next.config.js` file and redeploy your Amplify app: 

```js
module.exports = {
  target: 'experimental-serverless-trace'
}
```

**Important Note** As of today (Oct 11, 2021) this has not been rolled out to production yet. We plan to start rolling out very soon. Stay tuned. We will provide an update when it is GA.

**Comment by RealDrewKlayman** [comment]
> Hi everyone, we are adding support for deploying NextJS apps with the `experimental-serverless-trace` target. We have seen that this target fixes issues with the webpack bundle when using server side modules (i.e. argon).
> 
> In the interest of being extra careful and preserving backwards compatibility, we are not going to make this the default target yet. So for those having webpack issues, you will need to opt-in into this feature by specifying the target in your `next.config.js` file and redeploy your Amplify app:
> 
> ```js
> module.exports = {
>   target: 'experimental-serverless-trace'
> }
> ```
> 
> **Important Note** As of today (Oct 11, 2021) this **has not** been rolled out to production yet. We plan to start rolling out very soon. Stay tuned. We will provide an update when it is GA.

Thank you.

We'll give that a try when it is rolled out.

**Comment by gopeter** [comment]
Great, thanks a lot!

**Comment by gopeter** [comment]
I'm still not able to deploy my app to Amplify, even with `experimental-serverless-trace` and `11.1.3-canary`. 

```
Failed to compile.
./node_modules/@next/react-refresh-utils/ReactRefreshWebpackPlugin.js
Module not found: Can't resolve 'webpack' in '/codebuild/output/src113602678/src/myproject-website/frontend/node_modules/@next/react-refresh-utils'
Import trace for requested module:
./node_modules/next/dist/build/webpack-config.js
./node_modules/next/dist/server/dev/hot-reloader.js
./node_modules/next/dist/server/dev/next-dev-server.js
./node_modules/next/dist/server/next.js
./src/pages/index.tsx
./node_modules/next/dist/build/webpack/loaders/next--loader/index.js?page=%2F&absolutePagePath=private-next-pages%2Findex.tsx&absoluteAppPath=private-next-pages%2F_app.tsx&absoluteDocumentPath=private-next-pages%2F_document.tsx&absoluteErrorPath=next%2Fdist%2Fpages%2F_error&absolute404Path=private-next-pages%2F404.tsx&distDir=private-dot-next&buildId=MNnz-KhX-XZajd-0wLY6u&assetPrefix=&generateEtags=true&poweredByHeader=true&canonicalBase=&basePath=&runtimeConfig=redacted!
./node_modules/next/dist/compiled/@vercel/nft/LICENSE
Module parse failed: Unexpected token (1:10)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> Copyright 2019 Vercel, Inc.
|
| Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
Import trace for requested module:
./node_modules/next/dist/compiled/@vercel/nft/ sync ^\.\/.*$
./node_modules/next/dist/compiled/@vercel/nft/index.js
./node_modules/next/dist/build/webpack/plugins/next-trace-entrypoints-plugin.js
./node_modules/next/dist/build/webpack-config.js
./node_modules/next/dist/server/dev/hot-reloader.js
./node_modules/next/dist/server/dev/next-dev-server.js
./node_modules/next/dist/server/next.js
./src/pages/index.tsx
./node_modules/next/dist/build/webpack/loaders/next--loader/index.js?page=%2F&absolutePagePath=private-next-pages%2Findex.tsx&absoluteAppPath=private-next-pages%2F_app.tsx&absoluteDocumentPath=private-next-pages%2F_document.tsx&absoluteErrorPath=next%2Fdist%2Fpages%2F_error&absolute404Path=private-next-pages%2F404.tsx&distDir=private-dot-next&buildId=MNnz-KhX-XZajd-0wLY6u&assetPrefix=&generateEtags=true&poweredByHeader=true&canonicalBase=&basePath=&runtimeConfig=redacted!
./node_modules/next/dist/compiled/webpack/bundle5.js
Module not found: Can't resolve 'next/dist/build/webpack/plugins/terser-webpack-plugin' in '/codebuild/output/src113602678/src/myproject-website/frontend/node_modules/next/dist/compiled/webpack'
Import trace for requested module:
./node_modules/next/dist/compiled/webpack/webpack.js
./node_modules/next/dist/server/config-utils.js
./node_modules/next/dist/server/config.js
./node_modules/next/dist/server/next.js
./src/pages/index.tsx
./node_modules/next/dist/build/webpack/loaders/next--loader/index.js?page=%2F&absolutePagePath=private-next-pages%2Findex.tsx&absoluteAppPath=private-next-pages%2F_app.tsx&absoluteDocumentPath=private-next-pages%2F_document.tsx&absoluteErrorPath=next%2Fdist%2Fpages%2F_error&absolute404Path=private-next-pages%2F404.tsx&distDir=private-dot-next&buildId=MNnz-KhX-XZajd-0wLY6u&assetPrefix=&generateEtags=true&poweredByHeader=true&canonicalBase=&basePath=&runtimeConfig=redacted!
./node_modules/next/dist/compiled/webpack/webpack.js
Module not found: Can't resolve 'webpack5/lib/javascript/BasicEvaluatedExpression' in '/codebuild/output/src113602678/src/myproject-website/frontend/node_modules/next/dist/compiled/webpack'
Import trace for requested module:
./node_modules/next/dist/server/config-utils.js
./node_modules/next/dist/server/config.js
./node_modules/next/dist/server/next.js
./src/pages/index.tsx
./node_modules/next/dist/build/webpack/loaders/next--loader/index.js?page=%2F&absolutePagePath=private-next-pages%2Findex.tsx&absoluteAppPath=private-next-pages%2F_app.tsx&absoluteDocumentPath=private-next-pages%2F_document.tsx&absoluteErrorPath=next%2Fdist%2Fpages%2F_error&absolute404Path=private-next-pages%2F404.tsx&distDir=private-dot-next&buildId=MNnz-KhX-XZajd-0wLY6u&assetPrefix=&generateEtags=true&poweredByHeader=true&canonicalBase=&basePath=&runtimeConfig=redacted!
./node_modules/next/dist/compiled/webpack/webpack.js
Module not found: Can't resolve 'webpack5/lib/ModuleFilenameHelpers' in '/codebuild/output/src113602678/src/myproject-website/frontend/node_modules/next/dist/compiled/webpack'
Import trace for requested module:
./node_modules/next/dist/server/config-utils.js
./node_modules/next/dist/server/config.js
./node_modules/next/dist/server/next.js
./src/pages/index.tsx
./node_modules/next/dist/build/webpack/loaders/next--loader/index.js?page=%2F&absolutePagePath=private-next-pages%2Findex.tsx&absoluteAppPath=private-next-pages%2F_app.tsx&absoluteDocumentPath=private-next-pages%2F_document.tsx&absoluteErrorPath=next%2Fdist%2Fpages%2F_error&absolute404Path=private-next-pages%2F404.tsx&distDir=private-dot-next&buildId=MNnz-KhX-XZajd-0wLY6u&assetPrefix=&generateEtags=true&poweredByHeader=true&canonicalBase=&basePath=&runtimeConfig=redacted!
> webpack config.resolve.alias was incorrectly overridden. https://nextjs.org/docs/messages/invalid-resolve-alias
```

Lots of different error messages (I had to shorten the output and replace sensible information with `redacted`) ... last one is about `webpack config.resolve.alias was incorrectly overridden`, which is not the case. That's my `next.config.js`:

```
module.exports = {
  webpack5: true,
  eslint: {
    ignoreDuringBuilds: true,
  },
  i18n,
  serverRuntimeConfig: config,
  publicRuntimeConfig: {
    config: {
      frontend_url: config.config.frontend_url,
      backend_url: config.config.backend_url,
      cdn_url: config.config.cdn_url,
      craft: {
        cp_path: config.config.craft.cp_path,
      },
      s3: {
        bucket: config.config.s3.bucket,
      },
    },
    languages: languages,
  },
  webpack: (config) => {
    config.module.rules.push({
      test: /\.svg$/,
      use: ['@svgr/webpack'],
    })

    return config
  },
  async rewrites() {
    return rewrites
  },
}
```

My app ID is `d29c21rnokq3s3` if this helps. Any idea what I may doing wrong?

**Comment by CodySanders** [comment]
We are running into the same issue with Sentry. @ferdingler any updates yet on the fix?

@ovdahlberg did you happen to find a workaround for this?

**Comment by RealDrewKlayman** [comment]
@ferdingler This issue has started re-occuring yet without any configuration changes.

**Comment by RealDrewKlayman** [comment]
@ferdingler Also there isn't a canary for 105.

**Comment by Rafcin** [comment]
@RealDrewKlayman `AMPLIFY_NEXTJS_EXPERIMENTAL_TRACE` was added. Didn't work for me, but it does exist!

**Comment by lack-of-gravitas** [comment]
Same issue with next-auth

> @ferdingler This issue has started re-occuring yet without any configuration changes.
> ### UPDATE:
> 
> I was told that they actually reverted the ability to use the target for `experimental-serverless-trace`. So, this fix does no longer work.

**Comment by ronyfhebrian** [comment]
Any update on these? I'm just starting to add sentry to NextJS and hosting it to amplify and it crashed.

Saying Module not found for serveral modules like webpack, any help?

**Comment by adherb** [comment]
I am also facing the same issue using next-auth, I have tried to resolve using webpack 4, but unfortunately need webpack 5 for my app to work.

Has  there been any updates on this?

**Comment by pjaws** [comment]
Also experiencing this with Sentry/Webpack5.

**Comment by hloriii** [comment]
We have since launched improved support for Next.js versions 12 and 13 so this should no longer be an issue. Marking this as resolved.
